# Generated by Django 4.2.5 on 2023-09-29 09:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_order_datetime_create'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='datetime_create',
        ),
    ]
