# Generated by Django 4.2.5 on 2023-10-01 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_remove_order_datetime_create'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('w', 'Ожидает получения робота'), ('r', 'Передан в упаковочный цех')], default='w', max_length=1),
        ),
    ]
