# Generated by Django 4.2.5 on 2023-10-01 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('w', 'Ожидает получения робота'), ('g', 'Передан в упаковочный цех'), ('e', 'Передали письмо о наличие робота')], default='w', max_length=1),
        ),
    ]
